// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPL67lcKt9_c04pdVGX6sBur2dJvUO-nU',
    appId: '1:381210328781:android:0a37d24581daece17ef384',
    messagingSenderId: '381210328781',
    projectId: 'foodrecipe-8d34c',
    databaseURL: 'https://foodrecipe-8d34c-default-rtdb.firebaseio.com',
    storageBucket: 'foodrecipe-8d34c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA493Z1Zsw5sHYBj-f2OOZ1zR5PEp9I8rQ',
    appId: '1:381210328781:ios:e6ffc764f87d25c37ef384',
    messagingSenderId: '381210328781',
    projectId: 'foodrecipe-8d34c',
    databaseURL: 'https://foodrecipe-8d34c-default-rtdb.firebaseio.com',
    storageBucket: 'foodrecipe-8d34c.appspot.com',
    iosClientId: '381210328781-cnp790tal5ptiq8coa6csgfrekoa4f1u.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodrecipe',
  );
}
